x-common-net: &net
  networks:
    - elt_network

x-postgres-common-conf: &pg-common
  image: postgres:15
  <<: *net

x-airflow-common-conf: &airflow-common
  depends_on:
    - airflow_postgres
  <<: *net
  entrypoint: /bin/bash

x-airflow-common-env-var: &airflow-common-env-var
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow_postgres/airflow
  AIRFLOW__WEBSERVER__SECRET_KEY: secret

x-airflow-common-server-conf: &airflow-common-server
  build:
    context: .
    dockerfile: Dockerfile
  <<: *airflow-common
  user: root
  extra_hosts:
    - "host.docker.internal:host-gateway"
  volumes:
    - ./airflow/dags:${CONT_AIRFLOW_DAGS_DIR}
    - ./elt:${CONT_AIRFLOW_ELT_DIR}
    - ./custom_postgres:/opt/dbt
    - ~/.dbt:${CONT_DBT_PROFILE_DIR}
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    <<: *airflow-common-env-var
    AIRFLOW__WEBSERVER__RBAC: "True"
    HOST_HOME_DIR: ${HOST_HOME_DIR}
    HOST_DBT_DIR: ${HOST_PROJ_DIR}/custom_postgres
    ELT_DIR: ${CONT_AIRFLOW_ELT_DIR}
    DBT_PROFILE_DIR: ${CONT_DBT_PROFILE_DIR}
    DBT_PROJECT_DIR: ${CONT_DBT_PROJECT_DIR}


services:
  
  source_postgres:
    <<: *pg-common
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: source_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - source_db_data:/var/lib/postgresql/data
      - ./source_db_init/init.sql/:/docker-entrypoint-initdb.d/init.sql

  destination_postgres:
    <<: *pg-common
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: destination_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - destination_db_data:/var/lib/postgresql/data
  
  # elt_script:
  #   build:
  #     context: ./elt
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - source_postgres
  #     - destination_postgres
  #   <<: *net

  # dbt:
  #   image: ghcr.io/dbt-labs/dbt-postgres:1.9.latest
  #   command: 
  #     [ 
  #       "run", 
  #       "--profiles-dir", "${CONT_DBT_PROFILE_DIR}", 
  #       "--project-dir", "${CONT_DBT_PROJECT_DIR}" 
  #     ]
  #   volumes:
  #     - ./custom_postgres:${CONT_DBT_PROJECT_DIR}
  #     - ${HOST_HOME_DIR}/.dbt:${CONT_DBT_PROFILE_DIR}
  #   depends_on:
  #     elt_script:
  #       condition: service_completed_successfully
  #   <<: *net
  #   environment:
  #     DBT_PROFILE: custom_postgres
  #     DBT_TARGET: dev
  
  airflow_postgres:
    <<: *pg-common
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_db_data:/var/lib/postgresql/data
  
  airflow_init:
    image: apache/airflow:2.9.2
    <<: *airflow-common
    environment:
      <<: *airflow-common-env-var
    command: >
      -c "airflow db migrate && airflow users create --username airflow --firstname John --lastname Smith --role Admin --email johnsmith@example.com --password password"
    volumes:
      - ./airflow/dags:${CONT_AIRFLOW_DAGS_DIR}
  
  airflow_webserver:
    <<: *airflow-common-server
    ports:
      - "8080:8080"
    command: -c "airflow db migrate && airflow webserver"
  
  airflow_scheduler:
    <<: *airflow-common-server
    command: -c "airflow db migrate && airflow scheduler"

networks:
  elt_network:
    driver: bridge

volumes:
  source_db_data:
  destination_db_data:
  airflow_db_data: